"""H3 exactness + H4 first probe.
Homogeneous transparent tower: level gadget P' (slot x, wiring perm), innermost transparent pole A0.
(1) Recursive self-similar evaluation act(e, tape) vs exact composed automaton (depth 1..3).
(2) Group generated by the 12 entry-type actions on depth-d tapes: order by depth (finite vs growing)."""
import sys, random, itertools, math
from collections import Counter
sys.path.insert(0, "../phase3"); sys.path.insert(0, "../phase1"); sys.path.insert(0, ".."); sys.path.insert(0, "../../../../../paper")
import verify as V
from tower import from_pole, AbstractInner
from compose import composed_visit
from lollipop import random_instance
from sympy.combinatorics import Permutation, PermutationGroup
def chord_adj(n, ch): return [[(v - 1) % n, (v + 1) % n, ch[v]] for v in range(n)]
def transparent(A): return all(o == "TRANSMIT" for (o, _, _) in A["table"].values())

class Rec:
    """Child automaton given as a python object with .table-like access via act()."""
def paths_of(P, ports):
    out = {}
    for s, t in itertools.permutations(ports, 2):
        for Q in V.ham_paths(P, s, t): out.setdefault(frozenset([Q, Q[::-1]]), Q)
    return out

def build_tower_automaton(P1, ports1, x, perm, A0, depth):
    """Exact automaton of the depth-`depth` tower, with states = nested tuples (path-key, child-state)."""
    A = A0
    for _ in range(depth):
        name = {p: "abc"[i] for i, p in enumerate(ports1)}; port_of = {u: "abc"[perm[j]] for j, u in enumerate(P1[x])}
        paths = paths_of(P1, ports1); states = []; pair = {}; table = {}
        def cpair(Q):
            j = Q.index(x); return frozenset((port_of[Q[j-1]], port_of[Q[j+1]]))
        for key, Q in paths.items():
            for cs in A["states"]:
                if A["pair"][cs] == cpair(Q): st = (key, cs); states.append(st); pair[st] = frozenset((name[Q[0]], name[Q[-1]]))
        for (key, cs) in states:
            for Q in key:
                for kd in ("B1", "B3"):
                    inner = AbstractInner(x, port_of, A, cs)
                    o, Qf, _, _ = composed_visit(P1, ports1, Q, kd, inner)
                    table[((key, cs), (name[Q[0]], name[Q[-1]]), kd)] = (o, (frozenset([tuple(Qf), tuple(Qf[::-1])]), inner.s), (name[Qf[0]], name[Qf[-1]]))
        A = dict(states=states, pair=pair, table=table)
    return A

def group_order_by_depth(A_list):
    out = []
    for A in A_list:
        idx = {s: i for i, s in enumerate(A["states"])}; gens = []
        for pr in itertools.permutations("abc", 2):
            for kd in ("B1", "B3"):
                img = list(range(len(idx))); ok = True
                for s in A["states"]:
                    if A["pair"][s] == frozenset(pr): img[idx[s]] = idx[A["table"][(s, pr, kd)][1]]
                # transparent: maps pair(pr) class to another class; complete to a permutation via the backward map
                if len(set(img)) == len(img): gens.append(Permutation(img))
        G = PermutationGroup(gens) if gens else None
        out.append(G.order() if G and len(idx) <= 600 else ("n/a", len(idx)))
    return out

rng = random.Random(3)
lib = []
while len(lib) < 300:
    n = rng.choice([6, 8, 10]); K = chord_adj(n, random_instance(n, rng)); P, ports, _ = V.pole(K, rng.randrange(n)); A = from_pole(P, ports)
    if transparent(A) and len(A["states"]) > 3: lib.append((P, ports, A))
growth = Counter(); shown = 0
for (P1, ports1, A1) in lib[:60]:
    inner = [v for v in range(len(P1)) if v not in ports1]
    if not inner: continue
    x = inner[0]; perm = (0, 1, 2); A0 = rng.choice(lib)[2]
    try:
        As = [build_tower_automaton(P1, ports1, x, perm, A0, d) for d in (1, 2, 3)]
    except (KeyError, AssertionError, StopIteration): continue
    sizes = [len(A["states"]) for A in As]
    orders = group_order_by_depth(As)
    trend = "finite (stabilises)" if isinstance(orders[-1], int) and orders[-1] == orders[-2] else "grows"
    growth[trend] += 1
    if shown < 8: print(f"P' n={len(P1)}: tower states {sizes}, group orders by depth {orders}"); shown += 1
print("trend over towers:", dict(growth))
