"""Generate appendix_visits.tex: every move of the 12 visits of P0 = K - r, in K's vertex labels."""
import itertools, verify as V
verify_main_globals = V
V.KCYC = []
P0, ports, idx = V.pole(V.K, V.R); inv = {i: v for v, i in idx.items()}
name = {p: "abc"[i] for i, p in enumerate(ports)}; xname = {idx[u]: "abc"[V.PERM[j]] for j, u in enumerate(V.K[V.X])}
def L(v): return str(inv[v]) if isinstance(v, int) else "--"
rows = []
for s, t in itertools.permutations(ports, 2):
    Q = V.ham_paths(P0, s, t)[0]
    for kd in ("B1", "B3"):
        out, Qn, cost, moves = V.visit(P0, ports, Q, kd)
        mv = []
        for pieces, z, w, ss in moves[1:]:
            tag = ""
            if ss == idx[V.X]: tag = "$^{\\dagger}$"
            if w == idx[V.X]: tag = "$^{\\ddagger}$"
            mv.append(f"({L(z)},{L(w)}){tag}")
        entry_tag = "$^{\\dagger}$" if moves[0][3] == idx[V.X] else ""
        ps = V.passages(moves, idx[V.X], xname)
        rows.append((f"{name[s]}{name[t]}/{kd}", " ".join(str(inv[v]) for v in Q), entry_tag, " ".join(mv) or "--", cost,
                     ", ".join(f"{k[0]}/{k[1]}" for k in sorted(ps)), out[0]))
with open("appendix_visits.tex", "w") as f:
    f.write("% generated by gen_appendix.py -- do not edit by hand\n")
    f.write("\\begin{longtable}{@{}llp{6.2cm}rlc@{}}\n\\toprule\n")
    f.write("visit & $Q$ (vertices of $K$) & moves $(z,w)$ after the entry move & cost & passages through $x$ & out \\\\\n\\midrule\n\\endhead\n")
    for e, q, et, mv, c, ps, o in rows:
        f.write(f"{e}{et} & {q} & {mv} & {c} & {ps} & {o} \\\\\n")
    f.write("\\bottomrule\n\\end{longtable}\n")
print(open("appendix_visits.tex").read())
